---
kind: pipeline
type: exec
name: default

platform:
  os: darwin
  arch: amd64

trigger:
  repo:
  - saggit/memerybox
  branch:
  - dev
  event:
  - push

steps:
- name: deploy
  commands:
  - /Users/kelvince/py3env/bin/pip install -r requirements.txt
  - nohup /Users/kelvince/py3env/bin/python app.py &
